
version: "3.6"

services:


# eureka server 

  eureka-condidat-server:

    build:
      context: ./Eureka-server
      dockerfile: DockerFile

    container_name: eureka-condidat-server
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - bored-network
      
      
# mysql database      
  mysqldb:
    container_name: mysqldb
    image: mysql
    networks:
      - bored-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=jobDB
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    
    
    
# postgresql database    

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - bored-network    
    environment:
      POSTGRES_PASSWORD: root   
      POSTGRES_DB: candidat
      POSTGRES_USER: postgres
    ports:
      - "2345:5432"
      
      
#  job-service

  job-service:
    build:
      context: D:\projectSpring\Job
      dockerfile: DockerFile
    container_name: job-service
    image: job-service
    networks:
      - bored-network
    depends_on:
      - mysqldb
      - eureka-condidat-server
    ports:
      - "8091:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-condidat-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/jobDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=123456
  job-service-b:
    build:
      context: D:\projectSpring\Job
      dockerfile: DockerFile
    container_name: job-service-b
    image: job-service
    networks:
      - bored-network
    depends_on:
      - mysqldb
      - eureka-condidat-server
    ports:
      - "8092:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-condidat-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/jobDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=123456      
      
 #  candidat-service    
  candidat-service:

    build:
      context: D:\projectSpring\Candidat
      dockerfile: DockerFile
    container_name: candidat-service
    image: candidat-service
    networks:
      - bored-network
    depends_on:
      - postgres
      - eureka-condidat-server
    ports:
      - "8090:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-condidat-server:8761/eureka
      - spring.datasource.url=jdbc:postgresql://postgres:5432/candidat
      - spring.datasource.username=postgres
      - spring.datasource.password=root
   
networks:
  bored-network:
    name: bored-network
    
    
volumes:
  dbvol:

